
task:
  name: linux
  container:
    image: ubuntu
  test_script: echo "Hello World from Ubuntu!"
  build_script: make blink1-tool

task:
  name: macosx
  osx_instance:
    image: mojave-xcode
  test_script: echo "Hello World from macOS!"
  build_script: make blink1-tool
