
task:
  name: linux
  container:
    image: ubuntu:latest
  test_script: echo "Hello World from Ubuntu!"
  setup_os_script:
    - apt-get update && apt-get install -y build-essential git make gcc pkg-config libudev-dev
  setup_script:
    - git fetch --tags origin
    - make prep
  build_script:
    - make

task:
  name: macosx
  osx_instance:
    image: mojave-xcode
  test_script: echo "Hello World from macOS!"
  setup_script:
    - git fetch --tags origin
    - make prep
  build_script:
    - make

task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  test_script: echo "Hello World from Windows"
  setup_script:
    - env
    - $env:Path = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:Path
    - make CC=gcc prep
  build_script:
    - make CC=gcc
