#
# task:
#   name: linux
#   container:
#     image: ubuntu:latest
#   hello_script: echo "Hello World from Ubuntu!"
#   setup_os_script:
#     - apt-get update && apt-get install -y build-essential git make gcc pkg-config libudev-dev
#   setup_script:
#     - git fetch --tags origin
#     - make prep
#   build_script:
#     - make
#
# task:
#   name: macosx
#   osx_instance:
#     image: mojave-xcode
#   hello_script: echo "Hello World from macOS!"
#   setup_script:
#     - git fetch --tags origin
#     - make prep
#   build_script:
#     - make

task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  hello_script: echo "Hello World from Windows"
  setup_script:
    - git fetch --tags origin
  build_script:
    - set PATH=C:\tools\msys64\usr\bin\;c:\tools\msys64\mingw64\bin;%PATH%;
    - mingw32-make
  test_script:
    - blink1-tool --version
