#
# Build blink1-tool for linux, macosx, windows
#

task:
  name: linux
  environment:
    DEBIAN_FRONTEND: noninteractive
  container:
    image: ubuntu:latest
  setup_os_script:
    - apt-get update && apt-get install -y build-essential zip git make gcc pkg-config libudev-dev
  setup_script:
    - git fetch --tags origin
  build_script:
    - make
    - make package-all
  test_script:
    - ./blink1-tool --version
  artifacts:
    path: builds/*

task:
  name: macosx
  osx_instance:
    image: mojave-xcode
  setup_script:
    - git fetch --tags origin
  build_script:
    - make
    - make package-all
  test_script:
    - ./blink1-tool --version
  artifacts:
    path: builds/*

task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  setup_script:
    - set PATH=C:\tools\msys64\usr\bin;c:\tools\msys64\mingw64\bin;%PATH%
    - git fetch --tags origin
    - pacman -S --noconfirm zip unzip
  build_script:
    - set PATH=C:\tools\msys64\usr\bin;c:\tools\msys64\mingw64\bin;%PATH%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
#    - doskey make=mingw32-make.exe $*  # why doesn't this work
    - set MAKE=mingw32-make
    - mingw32-make
    - mingw32-make package-all
  test_script:
    - blink1-tool.exe --version
  artifacts:
    path: builds\*
