
task:
  name: linux
  container:
    image: ubuntu:latest
  test_script: echo "Hello World from Ubuntu!"
  setup_script:
    - apt-get update && apt-get install -y build-essential git make gcc pkg-config libudev-dev
    - git fetch origin master 
    - make prep
    - git tag
    - git tag 2>&1 | tail -1 | cut -f1 -d' '
  build_script:
    - make

task:
  name: macosx
  osx_instance:
    image: mojave-xcode
  test_script: echo "Hello World from macOS!"
  setup_script:
    - make prep
    - git tag 2>&1 | tail -1 | cut -f1 -d' '
  build_script:
    - make
